name: MyHomeRules
main: main.java.me.avankziar.myhomerules.spigot.MyHomeRules
version: 4
author: Avankziar
api-version: 1.16
description: A Rules accepting Plugin
website: https://www.spigotmc.org/resources/my-home-rules.79165/