name: MyHomeRules
main: main.java.me.avankziar.mhr.spigot.MyHomeRules
version: 6
author: Avankziar
api-version: 1.18
description: A Rules accepting Plugin
website: https://www.spigotmc.org/resources/my-home-rules.79165/
softdepend: [InterfaceHub]